"""Add user model

Revision ID: 0c2222cc07a4
Revises: 529fbd455992
Create Date: 2022-08-04 15:58:39.632391

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0c2222cc07a4'
down_revision = '529fbd455992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uuid', sa.String(length=36), nullable=True),
                    sa.Column('username', sa.String(length=48), nullable=False),
                    sa.Column('email', sa.String(length=54), nullable=False),
                    sa.Column('password', sa.String(length=254), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username'),
                    sa.UniqueConstraint('uuid')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
