"""Add one-to-many

Revision ID: 529fbd455992
Revises: 8806759b0ce4
Create Date: 2022-08-02 20:54:39.688938

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '529fbd455992'
down_revision = '8806759b0ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uuid', sa.String(length=36), nullable=True),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('uuid')
                    )
    op.create_table('book',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uuid', sa.String(length=36), nullable=True),
                    sa.Column('title', sa.String(length=120), nullable=False),
                    sa.Column('author_id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('release_date', sa.Date(), nullable=True),
                    sa.Column('publisher', sa.String(length=60), nullable=True),
                    sa.Column('language', sa.String(length=20), nullable=True),
                    sa.Column('rating', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('description'),
                    sa.UniqueConstraint('uuid')
                    )
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
                    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
                    sa.Column('author', sa.VARCHAR(length=80), nullable=False),
                    sa.Column('description', sa.TEXT(), nullable=False),
                    sa.Column('release_date', sa.DATE(), nullable=True),
                    sa.Column('publisher', sa.VARCHAR(length=60), nullable=True),
                    sa.Column('language', sa.VARCHAR(length=20), nullable=True),
                    sa.Column('rating', sa.FLOAT(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('description'),
                    sa.UniqueConstraint('uuid')
                    )
    op.drop_table('book')
    op.drop_table('author')
    # ### end Alembic commands ###
